export const GET_MY_DEVICES_STATISTICS_REQUEST = 'GET_MY_DEVICES_STATISTICS_REQUEST';
export const GET_MY_DEVICES_STATISTICS_SUCCESS = 'GET_MY_DEVICES_STATISTICS_SUCCESS';
export const GET_MY_DEVICES_STATISTICS_FAILURE = 'GET_MY_DEVICES_STATISTICS_FAILURE';
